var skills = [
     {
         "srcImg":"image/html.png",
         "nombre":"HTML",
         "porcentaje":"80%"
     },
     {
         "srcImg":"image/css.png",
         "nombre":"CSS",
         "porcentaje":"85%"
     },
     {
         "srcImg":"image/js.png",
         "nombre":"JAVASCRIPT",
         "porcentaje":"65%"
     },
     {
         "srcImg":"image/jquery.png",
         "nombre":"JQUERY",
         "porcentaje":"75%"
     },
     {
         "srcImg":"image/sass.svg",
         "nombre":"SASS",
         "porcentaje":"35%"
     },
     {
         "srcImg":"image/bootstrap.png",
         "nombre":"BOOTSTRAP",
         "porcentaje":"70%"
     },
     {
         "srcImg":"image/github.png",
         "nombre":"GITHUB",
         "porcentaje":"70%"
     },
     {
         "srcImg":"image/trello.png",
         "nombre":"TRELLO",
         "porcentaje":"75%"
     },
     {
         "srcImg":"image/responsive.png",
         "nombre":"RESPONSIVE",
         "porcentaje":"85%"
     },
     {
         "srcImg":"image/jquery.png",
         "nombre":"ANONIMO",
         "porcentaje":"50%"
     }
]

var proyects = [
    {
         "image":"image/gato.png",
         "name":"https://cinthia-mashiel.github.io/Gato-loco/"
     },
     {
         "image":"image/lyft.png",
         "name":"https://cinthia-mashiel.github.io/Lyft-jquery-2/"
     },
     {
         "image":"image/whatsapp.png",
         "name":"https://cinthia-mashiel.github.io/whatsapp-web/"
     },
     {
         "image":"image/creamy.png",
         "name":"https://cinthia-mashiel.github.io/creamy-theme/"
     },
     {
         "image":"image/bunny.png",
         "name":"https://cinthia-mashiel.github.io/bunny-love/"
     },
     {
         "image":"image/user.png",
         "name":"https://cinthia-mashiel.github.io/User-Testing/"
     }
]

var proyects2 = [
    {
         "image":"image/larepublica.png",
         "name":"...."
     },
     {
         "image":"image/app.png",
         "name":"https://cinthia-mashiel.github.io/lista-tareas/"
     },
     {
         "image":"image/edad.png",
         "name":"http://codepen.io/Mashiel/full/pRyJdj/"
     }
]