var skills = [
     {
         "srcImg":"image/html.png",
         "nombre":"HTML",
         "porcentaje":"90%"
     },
     {
         "srcImg":"image/css.png",
         "nombre":"CSS",
         "porcentaje":"95%"
     },
     {
         "srcImg":"image/js.png",
         "nombre":"JAVASCRIPT",
         "porcentaje":"80%"
     },
     {
         "srcImg":"image/jquery.png",
         "nombre":"JQUERY",
         "porcentaje":"85%"
     },
     {
         "srcImg":"image/sass.svg",
         "nombre":"SASS",
         "porcentaje":"80%"
     },
     {
         "srcImg":"image/bootstrap.png",
         "nombre":"BOOTSTRAP",
         "porcentaje":"85%"
     },
     {
         "srcImg":"image/gulp.png",
         "nombre":"GULP",
         "porcentaje":"70%"
     },
     {
         "srcImg":"image/node.png",
         "nombre":"NODE.JS",
         "porcentaje":"40%"
     },
     {
         "srcImg":"image/ionic.png",
         "nombre":"IONIC",
         "porcentaje":"45%"
     },
     {
         "srcImg":"image/github.png",
         "nombre":"GITHUB",
         "porcentaje":"80%"
     },
     {
         "srcImg":"image/trello.png",
         "nombre":"TRELLO",
         "porcentaje":"85%"
     },
     {
         "srcImg":"image/responsive.png",
         "nombre":"RESPONSIVE",
         "porcentaje":"90%"
     }
]

var proyects = [
    {
         "image":"image/gato.png",
         "name":"https://cinthia-mashiel.github.io/Gato-loco/"
     },
     {
         "image":"image/lyft.png",
         "name":"https://cinthia-mashiel.github.io/Lyft-jquery-2/"
     },
     {
         "image":"image/whatsapp.png",
         "name":"https://cinthia-mashiel.github.io/whatsapp-web/"
     },
     {
         "image":"image/creamy.png",
         "name":"https://cinthia-mashiel.github.io/creamy-theme/"
     },
     {
         "image":"image/bunny.png",
         "name":"https://cinthia-mashiel.github.io/bunny-love/"
     },
     {
         "image":"image/user.png",
         "name":"https://cinthia-mashiel.github.io/User-Testing/"
     }
]

var proyects2 = [
    {
         "image":"image/larepublica.png",
         "name":"https://cinthia-mashiel.github.io/La-republica/."
     },
     {
         "image":"image/app.png",
         "name":"https://cinthia-mashiel.github.io/lista-tareas/"
     },
     {
         "image":"image/edad.png",
         "name":"http://codepen.io/Mashiel/full/pRyJdj/"
     }
]