var jsonArray = [
     {
         "srcImg":"image/html.png",
         "nombre":"HTML",
         "porcentaje":"80%"
     },
     {
         "srcImg":"image/css.png",
         "nombre":"CSS",
         "porcentaje":"85%"
     },
     {
         "srcImg":"image/js.png",
         "nombre":"JAVASCRIPT",
         "porcentaje":"65%"
     },
     {
         "srcImg":"image/jquery.png",
         "nombre":"JQUERY",
         "porcentaje":"75%"
     },
     {
         "srcImg":"image/sass.svg",
         "nombre":"SASS",
         "porcentaje":"35%"
     },
     {
         "srcImg":"image/bootstrap.png",
         "nombre":"BOOTSTRAP",
         "porcentaje":"70%"
     },
     {
         "srcImg":"image/github.png",
         "nombre":"GITHUB",
         "porcentaje":"70%"
     },
     {
         "srcImg":"image/trello.png",
         "nombre":"TRELLO",
         "porcentaje":"75%"
     },
     {
         "srcImg":"img-responsive",
         "nombre":"RESPONSIVE",
         "porcentaje":"85%"
     },
     {
         "srcImg":"img-responsive",
         "nombre":"ANONIMO",
         "porcentaje":"50%"
     }
]